In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from datetime import datetime, date

In [26]:
df = pd.read_csv("HRDataSet.csv")
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [27]:
df.values.tolist()
print(df)

                Employee_Name  EmpID  MarriedID  MaritalStatusID  GenderID  \
0         Adinolfi, Wilson  K  10026          0                0         1
1    Ait Sidi, Karthikeyan     10084          1                1         1
2           Akinkuolie, Sarah  10196          1                1         0
3                Alagbe,Trina  10088          1                1         0
4            Anderson, Carol   10069          0                2         0
..                        ...    ...        ...              ...       ...
306            Woodson, Jason  10135          0                0         1
307        Ybarra, Catherine   10301          0                0         0
308          Zamora, Jennifer  10010          0                0         0
309               Zhou, Julia  10043          0                0         0
310             Zima, Colleen  10271          0                4         0

     EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  Salary  ...  \
0              1       5            4                       0   62506  ...
1              5       3            3                       0  104437  ...
2              5       5            3                       0   64955  ...
3              1       5            3                       0   64991  ...
4              5       5            3                       0   50825  ...
..           ...     ...          ...                     ...     ...  ...
306            1       5            3                       0   65893  ...
307            5       5            1                       0   48513  ...
308            1       3            4                       0  220450  ...
309            1       3            3                       0   89292  ...
310            1       5            3                       0   45046  ...

        ManagerName  ManagerID  RecruitmentSource PerformanceScore  \
0    Michael Albert       22.0           LinkedIn          Exceeds
1        Simon Roup        4.0             Indeed      Fully Meets
2    Kissy Sullivan       20.0           LinkedIn      Fully Meets
3      Elijiah Gray       16.0             Indeed      Fully Meets
4    Webster Butler       39.0      Google Search      Fully Meets
..              ...        ...                ...              ...
306  Kissy Sullivan       20.0           LinkedIn      Fully Meets
307  Brannon Miller       12.0      Google Search              PIP
308      Janet King        2.0  Employee Referral          Exceeds
309      Simon Roup        4.0  Employee Referral      Fully Meets
310   David Stanley       14.0           LinkedIn      Fully Meets

     EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0                4.60               5                    0
1                4.96               3                    6
2                3.02               3                    0
3                4.84               5                    0
4                5.00               4                    0
..                ...             ...                  ...
306              4.07               4                    0
307              3.20               2                    0
308              4.60               5                    6
309              5.00               3                    5
310              4.50               5                    0

    LastPerformanceReview_Date DaysLateLast30 Absences
0                    1/17/2019              0        1
1                    2/24/2016              0       17
2                    5/15/2012              0        3
3                     1/3/2019              0       15
4                     2/1/2016              0        2
..                         ...            ...      ...
306                  2/28/2019              0       13
307                   9/2/2015              5        4
308                  2/21/2019              0       16
309                   2/1/2019              0       11
310                  1/30/2019              0        2

[311 rows x 36 columns]

In [28]:
from pandas import *

# Creating a list of date of birth
dob = {'df.DOB': []}
  
# Creating dataframe
df = pd.DataFrame(data = dob)
  
# This function converts given date to age
def age(born):
    born = datetime.strptime(born, "%d/%m/%Y").date()
    today = date.today()
    return today.year - born.year - ((today.month, 
                                      today.day) < (born.month, 
                                                    born.day))
  
df['Age'] = df['DOB'].apply(age)
  
display(df)

KeyError: 'DOB'